security:
  basic:
    enabled: false

spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:/home/zbroby/IdeaProjects/db/mrbs
    username: test
    password: test
    driver-class-name: org.h2.Driver

  main:
    web-environment: false
